### PR TITLE
1954 Creating a new segmentation mask on an MPR view fix

### LINKED ISSUE #1954: Bug: Creating a new segmentation mask on an MPR view will draw on the wrong slice
To reproduce:
1. Load a series into the test viewer
2. Switch the layout to MPR
3. Navigate to a different slice in one of the MPR views
4. Select the brush tool
5. Draw on that same MPR view

Expected behavior:
The tool will draw on the slice currently being displayed.

Actual behavior:
The view will navigate to the center slice and the tool will draw there instead.

Demonstration:
Image

### PR DESCRIPTION
**Pull request by plt-joey**
Fixes #1954

A symptom-first fix. If there is a better place to fix this let me know

### CODE REVIEW

File: src/tools/brush.js [hunk 1]
```diff
@@ -1044,6 +1045,12 @@ export class Brush extends EventTarget {
       sliceMeta
     );
 
+    // this.#displayMask causes the position to get reset,
```
Comment (ivmartel) [inline src/tools/brush.js:1048]: couldn't the set position be made in the `if (viewController.equalImageMeta(searchMaskMeta))` part that calls the `displayMask`?

**Comment by ivmartel** [comment]
Looks good, thanks!
